### PR TITLE
Feature/chat 72 add token auth to api routes

### PR DESCRIPTION
**Pull request by WataNekko**
Roughly adds authentication to the available API routes. Most likely a draft version since the API routes are currently all over the place. We need to redesign the API spec and reimplement them later.

### CODE REVIEW

**Review by MapleThanh — APPROVED** [review]
Goodjob lil bro, i love u

**Comment by WataNekko** [comment]
> Goodjob lil bro, i love u

lol thanks beo

**Review by XkhangNguyen — APPROVED** [review]
Approve first read later. I promise @@

**Comment by WataNekko** [comment]
> Approve first read later. I promise @@

😡

**Pull request merged**
